### ISSUE TITLE
Running lsst v11.0 demo on Ubuntu 14.04 does not work

### ISSUE THREAD

**Issue by airnandez** [airnandez/lsst-cvmfs#2]
We have observed that running the v11.0 demo on Ubuntu 14.04 using the binary distribution does not work. The binary distribution of v11.0 was built on CentOS 7.

This is the error message:

```
Setting up: astrometry_net_data             Flavor: Linux64    Version: LOCAL:/home/ubuntu/lsst/lsst_dm_stack_demo-11.0/astrometry_net_data
Traceback (most recent call last):
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/obs_sdss/11.0+2/bin/processCcdSdss.py", line 23, in <module>
    from lsst.obs.sdss.processCcdSdss import ProcessCcdSdssTask
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/obs_sdss/11.0+2/python/lsst/obs/sdss/__init__.py", line 23, in <module>
    from sdssMapper import *
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/obs_sdss/11.0+2/python/lsst/obs/sdss/sdssMapper.py", line 24, in <module>
    import lsst.pex.policy as pexPolicy
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/pex_policy/11.0/python/lsst/pex/policy/__init__.py", line 23, in <module>
    from policyLib import *
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/pex_policy/11.0/python/lsst/pex/policy/policyLib.py", line 34, in <module>
    _policyLib = swig_import_helper()
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/pex_policy/11.0/python/lsst/pex/policy/policyLib.py", line 30, in swig_import_helper
    _mod = imp.load_module('_policyLib', fp, pathname, description)
  File "/cvmfs/lsst.in2p3.fr/software/linux-x86_64/lsst-v11.0/Linux64/base/11.0/python/lsstimport.py", line 102, in imp_load_module
    module = orig_imp_load_module(name, *args)
ImportError: libicudata.so.50: cannot open shared object file: No such file or directory
```

**Comment by airnandez** [comment]
This issue has been traced to a problem building `boost` with Unicode support in the CentOS 7 machine used for building the binary. We are looking at alternative ways to build `boost` without Unicode.

**Comment by airnandez** [comment]
See ticket LSST [DM-4006](https://jira.lsstcorp.org/browse/DM-4006).

**Comment by airnandez** [comment]
This problem is fixed. The `lsst-v11.0` for Linux was built on CentOS 7 without support for Unicode for `boost` and it works on Ubuntu 14.04.
